[package]
name = "qing"
edition = "2021"
version = "0.1.0"
authors = ["OST-Gh"]
description = "A music player which's name is a pun on the word queueing."
keywords = [""]
categories = [""]

[dependencies]
oxygen = { path = "../elem/oxygen", features = ["time"] }
carbon = { path = "../elem/carbon" }
nitrogen = { path = "../elem/nitrogen" }
serde = { version = "1", features = ["derive"], default-featurse = false }
toml = { version = "*", features = ["parse"], default-features = false }
rodio = { version = "*", features = ["mp3", "wav"], default-features = false }
fastrand = "2"

[profile.release]
opt-level = "z"
debug = false
split-debuginfo = "unpacked"
strip = true
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1

[profile.release.package."*"]
opt-level = "z"
debug = false
split-debuginfo = "unpacked"
strip = true
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
