[package]
name = "qing"
edition = "2021"
version = "1.0.0"
authors = ["OST-Gh"]
description = "A (hopefully) minimalist toml based song shuffler"
keywords = ["audio", "playback", "toml"]
categories = ["Command line utilities"]
repository = "https://github.com/OST-Gh/qing.git"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
serde = { version = "1", features = ["derive"], default-features = false }
toml = { version = "*", features = ["parse"], default-features = false }
chrono = { version = "*", features = ["clock"], default-features = false }
crossterm = { version = "*", default-features = false }
rodio = "*"
lofty = "*"
crossbeam-channel = "*"
fastrand = "2"

[profile.release]
opt-level = "z"
debug = false
split-debuginfo = "unpacked"
strip = true
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1

[profile.release.package."*"]
opt-level = "z"
debug = false
split-debuginfo = "unpacked"
strip = true
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
