done = []

[[todo]]
name = "Deccrease memory footprint if even possible"
group = "global"

[[todo]]
name = "Search for bugs"
group = "global"

[[todo]]
name = "add is_terminal checks in without creating multiple functions nor if checks in the log macro"
group = "global"
