done = []

[[todo]]
name = "Add Spotify Support"
group = "global"

[[todo]]
name = "Optimize Idle-Wake-Ups on MacOS"
group = "global"

[[todo]]
name = "Deccrease memory footprint if even possible"
group = "global"

[[todo]]
name = "Search for bugs"
group = "global"

[[todo]]
name = "make a better no-args message with proper formatting and colour"
group = "global"
