done = []

[[todo]]
	group = "global"
	name  = "Deccrease memory footprint if even possible"

[[todo]]
	group = "global"
	name  = "Search for bugs"

[[todo]]
	group   = "global"
	name    = "Merge in_out and songs"
	purpose = "lessen the file crossing imports"

[[todo]]
	group = "features"
	name  = "Create a help flag"

[[todo]]
	group = "features"
	name  = "create a token specialiser for Flags (eg: +nightly)"

[[todo]]
	group = "features"
	name  = "crate a long name flag part (idk how)"

[[todo]]
	group = "global"
	name  = "update docs"
