done = []

[[todo]]
name = "Deccrease memory footprint if even possible"
group = "global"

[[todo]]
name = "Search for bugs"
group = "global"

[[todo]]
name = "Merge in_out and songs"
group = "global"
purpose = "lessen the file crossing imports"
