[[todo]]
name = "Deccrease memory footprint if even possible"
group = "global"

[[todo]]
name = "Search for bugs"
group = "global"

[[todo]]
name = "Create a help flag"
group = "features"

[[todo]]
name = "create a token specialiser for Flags (eg: +nightly)"
group = "features"

[[todo]]
name = "crate a long name flag part (idk how)"
group = "features"

[[todo]]
name = "update docs"
group = "global"

[[done]]
name = "Merge in_out and songs"
group = "global"
purpose = "lessen the file crossing imports"
